### ISSUE TITLE
reformat of source

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite-manager#26]
Is someone interested in doing a quick reformat of all of the source? There are inconsistencies in the formatting...For example, please look at [InstanceDataDAOCassandra.java](https://github.com/Netflix/dynomite-manager/blob/1036d0f540e9754bf84bbf8d5760bb7dd5d4b1e6/dynomitemanager/src/main/java/com/netflix/dynomitemanager/identity/InstanceDataDAOCassandra.java)

I can quickly do this as my editor updates everything to a standard automatically.

**Comment by ipapapa** [comment]
Can you point to some examples of the inconsistencies?

**Comment by akbarahmed** [comment]
Please note that I am not fastidious when it comes to style. However, in this case I think a quick run of a formatting tool will help improve consistency in whitespace / formatting.

### Source code formatter

Google released a source code formatter: https://github.com/google/google-java-format

I believe there is also a source code formatter in Eclipse that can be used from the command line (I'd have to look into this).

If we pick a CLI tool, we can easily add a pre-commit hook to ensure that all commits conform to the same style.

### Examples

The following are some examples from the first 3 source files. 

- [DynomitemanagerConfiguration.java](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/defaultimpl/DynomitemanagerConfiguration.java)
    - line 353 vs. 366: tabs and spaces in mixed use. Repeats in multiple methods.
- [FloridaProcessManager.java](dynomitemanager/src/main/java/com/netflix/dynomitemanager/defaultimpl/FloridaProcessManager.java)
    - lines 204, 205: not indented properly
    - same mixed use of tabs, spaces, trailing whitespace
- [FloridaStandardTuner.java](dynomitemanager/src/main/java/com/netflix/dynomitemanager/defaultimpl/FloridaStandardTuner.java)
    - line 142 indentation level is wrong
    - line 149 indentation level is wrong

**Comment by ipapapa** [comment]
You are right. Feel free to do it across the board, or otherwise I will work on it as we change files using the `Java Convention`.

**Comment by akbarahmed** [comment]
I have created a branch that shows the Eclipse Java Conventions applied to every .java file. As a result, it's a lot of change in a single commit.

- Eclipse Java Conventions style: https://github.com/DynomiteDB/dynomite-manager/tree/coding-style-eclipse

If this looks okay then I'll issue a PR.

**Comment by ipapapa** [comment]
Can we use Java convention instead of eclipse style? Most folks are using Intellij IDEA.

**Comment by ipapapa** [comment]
I find strange and incorrect the use of ` <p/>` inside the licenses. If we are to use HTML tags then we should use them in the correct way. Not sure how much manual effort it is to remove them. Thoughts>

**Comment by akbarahmed** [comment]
Agreed. I plan to manually clean up that stuff along with any other minor formatting issues.

**Comment by ipapapa** [comment]
ok cool, let me know and I take a look in the PR.
