### ISSUE TITLE
Should be SimpleDBConfigSource, not PropertiesConfigSource

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite-manager#29]
Please look at the highlighted line: [DefaultConfigSource.java#L24](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/sidecore/DefaultConfigSource.java#L24)

Shouldn't `PropertiesConfigSource simpleDBConfigSource` be `SimpleDBConfigSource simpleDBConfigSource`.

```java
@Inject
public DefaultConfigSource(final SimpleDBConfigSource simpleDBConfigSource,
						final PropertiesConfigSource propertiesConfigSource,
						final SystemPropertiesConfigSource systemPropertiesConfigSource) {

	super(simpleDBConfigSource, propertiesConfigSource, systemPropertiesConfigSource);

}
```

If yes, I can quickly make this change.

**Comment by ipapapa** [comment]
Yes that is a good catch.
