### ISSUE TITLE
stop() should be start start(), cleanup of return values, add retry

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite-manager#31]
@ipapapa Please look at [FloridaProcessManager.java#L209](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/defaultimpl/FloridaProcessManager.java#L209)

line 209, should be `this.dynProcess.start();`.

Also, the behavior of the callers of `dynomiteCheck()` is not what I would expect.

See [WarmBootstrapTask.java#L116](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/sidecore/utils/WarmBootstrapTask.java#L116)

If `dynomiteCheck()` passes the heath check (i.e. dynomite is running), it then proceeds to try to start it again.

# Proposed changes

I have created a new branch with some proposed changes. I will test my code in the morning and then submit a PR.

You can view my proposed changes at https://github.com/Netflix/dynomite-manager/compare/dev...DynomiteDB:bugfix30

**Comment by ipapapa** [comment]
The fact that it tries to start it twice in the `WarmBootstrapTask` does not have any bad effect, but it is definitely not needed. So that needs to be fixed. 

`dynomiteCheck()` seems kind of correct, I mean if the redis check fails there is no reason to keep a zombie Dynomite running.

**Comment by akbarahmed** [comment]
Would it make sense to have `dynomiteCheck()` restart both Redis and Dynomite is the health check fails? For example, if the HC fails, then we attempt to stop dynomite, stop redis, start redis, start dynomite. 

The above would make sense if dynomite and redis failed due to a transient condition, but would cause 2 extra failed start attempts if either component failed due to a permanent error.

One case where recycling both dynomite and redis may make sense is if the 1M messages limit is reached. 

As an FYI, the original comment for `dynomiteCheck()` said that it performed an auto-restart.

**Comment by akbarahmed** [comment]
I get it now. I'll delete my branch.

Also, I'll update `WarmBootstrapTask` in my next JavaDoc PR tonight. It's a minor change where I will remove the extra start and replace it with a log message.

**Comment by ipapapa** [comment]
It sounds to me that https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/sidecore/utils/WarmBootstrapTask.java#L116 is also wrong. It is needs to be the opposite i.e. if Dynomite failed to start then try to restart Dynomite. I suggest you make those two fixes in a separate PR than the JavaDocs but if you have already done the work and it is hard to rollback don't worry about it.
