### ISSUE TITLE
Bug: getRacks() will not return the list of AZs from the local Region

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite-manager#35]
# DynomitemanagerConfiguration.java
1. `CONFIG_AVAILABILITY_ZONES` is only used in `getZones()`.
2. `getZones()` is never used, so it can be removed. Therefore, `CONFIG_AVAILABILITY_ZONES` can be removed.
3. **BUG**: `setDefaultRACList()` sets the value of `DEFAULT_AVAILABILITY_ZONES`, but should set the value of `DEFAULT_AVAILABILITY_RACKS`. 
   - The reason is that `getZones()`, which returns `DEFAULT_AVAILABILITY_ZONES` is never used.
   - However, `getRacks()`, which is used by `AWSMembership.java` returns `DEFAULT_AVAILABILITY_RACKS` which is (should be) the list of AZs within the server's Region.
4. After fixing the bug, then `DEFAULT_AVAILABILITY_ZONES` will never be used and can be removed.

I'll push this bug fix as one of the commits in my PR for configuration.

**Comment by ipapapa** [comment]
This is great, it sounds good to me.

**Comment by ipapapa** [comment]
I am closing this as soon I will post the new version of Dynomite Manager that will be Archaius 2 ready and a way simpler way to configure Racks and Zones.
