### ISSUE TITLE
Extraneous conditional

### ISSUE THREAD

**Issue by akbarahmed** [Netflix/dynomite-manager#36]
It appears that the conditional at [LocalHostsSupplier.java#L49](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/supplier/LocalHostsSupplier.java#L49) will always be true and can therefore be removed. This also means that that the `else` condition is unreachable.

The value of `bootCluster` is set on line 44 as `String bootCluster = config.getBootClusterName();`.

And, the value of `clusterName` used on line 49 is set in [InstanceDataDAOCassandra.java#L91](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/identity/InstanceDataDAOCassandra.java#L91) and then used in the following invocations of `getSupplier()`: [InstanceDataDAOCassandra.java#L354](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/identity/InstanceDataDAOCassandra.java#L354)

**Comment by ipapapa** [comment]
Need to review it carefully, but you are most probably right.

**Comment by ipapapa** [comment]
@akbarahmed  I think @diegopacheco added this in order to run a local Cassandra: https://github.com/Netflix/dynomite-manager/commit/f0fcebe1b9c23fca964867ade759ada1f73e9c8b

@diegopacheco can you please take a look in the above?

**Comment by diegopacheco** [comment]
@ipapapa 

Cassandra persistence is working for me just fine. Not sure If the code goes or not with that particular path. My change should have no relation with that if. Just ask if you or @akbarahmed do changes with careful because we are using this and it works for us.  If I can help more with something else please let me know... 

Cheers,
Diego Pacheco

**Comment by ipapapa** [comment]
@diegopacheco according to the commit history that you can see if you open the https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/supplier/LocalHostsSupplier.java#L49 was not modified and it is still in the initial way you have added that part of the code.

**Comment by akbarahmed** [comment]
Adding the following as a note to myself. The `else` condition is only used for unit test.

I have left  a `todo` in the code to update both the class and the test.

**Comment by ipapapa** [comment]
The lines of the Extraneous condition are a little off. I have though fixed the `if` statement that looked a little off. https://github.com/Netflix/dynomite-manager/commit/ed2b6cfa34fceea9157dc523e2c91ba2ffa9e2e5 We do not need to check every time if the FP is `null` as if it is not set will result into using the default value.
