### ISSUE TITLE
No implementation for com.netflix.dynomitemanager.identity.InstanceEnvIdentity was bound.

### ISSUE THREAD

**Issue by cyrusmith** [Netflix/dynomite-manager#7]
When trying to start the app either via gradle jettyRun task or by deploying to tomcat the error comes up:
```
com.google.inject.CreationException: Guice creation errors:

1) No implementation for com.netflix.dynomitemanager.identity.InstanceEnvIdentity was bound.
  while locating com.netflix.dynomitemanager.identity.InstanceEnvIdentity
    for parameter 2 at com.netflix.dynomitemanager.sidecore.aws.AWSMembership.<init>(AWSMembership.java:66)
  while locating com.netflix.dynomitemanager.identity.IMembership
    for parameter 1 at com.netflix.dynomitemanager.identity.InstanceIdentity.<init>(InstanceIdentity.java:80)
  while locating com.netflix.dynomitemanager.identity.InstanceIdentity
    for parameter 1 at com.netflix.dynomitemanager.defaultimpl.FloridaStandardTuner.<init>(FloridaStandardTuner.java:61)
  at com.netflix.dynomitemanager.defaultimpl.InjectedWebListener$DynomiteGuiceModule.configure(InjectedWebListener.java:116)

2) Could not find a suitable constructor in com.netflix.discovery.DiscoveryClient. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.netflix.discovery.DiscoveryClient.class(DiscoveryClient.java:91)
  while locating com.netflix.discovery.DiscoveryClient
    for parameter 0 at com.netflix.dynomitemanager.supplier.EurekaHostsSupplier.<init>(EurekaHostsSupplier.java:54)
  at com.netflix.dynomitemanager.defaultimpl.InjectedWebListener$DynomiteGuiceModule.configure(InjectedWebListener.java:123)
```

**Comment by diegopacheco** [comment]
@cyrusmith 

IMHO this is not a bug. You need provide Dynomite Manager configuration in order to get it Running.

You need tell Dynomite Manager IF you are running on AWS. Most of people are running on VPC.

So you can do this: 

1. Create This class.

[com.netflix.dynomitemanager.identity.DefaultVpcInstanceEnvIdentity]
```java
package com.netflix.dynomitemanager.identity;

public class DefaultVpcInstanceEnvIdentity implements InstanceEnvIdentity {
	
	public DefaultVpcInstanceEnvIdentity() {}
	
	@Override
	public Boolean isClassic() {
		return false;
	}
	
	@Override
	public Boolean isDefaultVpc() {
		return true;
	}
	
	@Override
	public Boolean isNonDefaultVpc() {
		return false;
	}
	
}

```

2. Add a Guice injection.

[com.netflix.dynomitemanager.defaultimpl.InjectedWebListener]
```java
    public static class DynomiteGuiceModule extends AbstractModule
    {
        @Override
        protected void configure()
        {
            logger.info("**Binding OSS Config classes.");
            binder().bind(IConfiguration.class).to(DynomitemanagerConfiguration.class);
            binder().bind(ProcessTuner.class).to(FloridaStandardTuner.class);
            binder().bind(IAppsInstanceFactory.class).to(CassandraInstanceFactory.class);
            binder().bind(SchedulerFactory.class).to(StdSchedulerFactory.class).asEagerSingleton();
            binder().bind(ICredential.class).to(IAMCredential.class);
            binder().bind(IFloridaProcess.class).to(FloridaProcessManager.class);
            binder().bind(IStorageProxy.class).to(RedisStorageProxy.class);
            binder().bind(InstanceDataRetriever.class).to(AwsInstanceDataRetriever.class);
            binder().bind(HostSupplier.class).to(EurekaHostsSupplier.class);
            binder().bind(InstanceEnvIdentity.class).to(DefaultVpcInstanceEnvIdentity.class).asEagerSingleton();

 //           binder().bind(GuiceContainer.class).asEagerSingleton();
 //           binder().bind(GuiceJobFactory.class).asEagerSingleton();

        }
    }
```

Cheers,
Diego Pacheco

**Comment by cyrusmith** [comment]
@diegopacheco, thanks. It still might be reasonable to provide some dummy implementation to avoid any further confusion.

**Comment by diegopacheco** [comment]
@cyrusmith Make sense. I will do a PR with this code.  IF makes sense for @ipapapa

**Comment by ipapapa** [comment]
@diegopacheco Yes, it does make sense. I have skipped that in my latest commits for VPC. I am so sorry.

**Comment by ipapapa** [comment]
@cyrusmith I have added the requested fix: https://github.com/Netflix/dynomite-manager/pull/8 let me know if it works for you and I will merge it to dev.

@diegopacheco please take a look. I have defaulted the Listener to local implementations based on the fact that most people tend to run `./gradlew jettyRun` to test dynomite-manager. What do you think about this?

**Comment by cyrusmith** [comment]
@ipapapa I think this particular issue is resolved. I still cannot start it locally anyway.
When run with command:
```
export EC2_REGION=us-east-1; export ASG_NAME=foobar; ./gradlew -Dorg.gradle.debug=true jettyRun
```

I get:
```
Caused by: com.amazonaws.AmazonClientException: Unable to load credentials from Amazon EC2 metadata service
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.handleError(InstanceProfileCredentialsProvider.java:244)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.loadCredentials(InstanceProfileCredentialsProvider.java:225)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:124)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11112)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeAvailabilityZones(AmazonEC2Client.java:4505)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeAvailabilityZones(AmazonEC2Client.java:4517)
	at com.netflix.dynomitemanager.defaultimpl.DynomitemanagerConfiguration.setDefaultRACList(DynomitemanagerConfiguration.java:438)
	at com.netflix.dynomitemanager.defaultimpl.DynomitemanagerConfiguration.initialize(DynomitemanagerConfiguration.java:269)
	at com.netflix.dynomitemanager.defaultimpl.InjectedWebListener.getInjector(InjectedWebListener.java:77)
```

This is something I know how to deal with and it's a whole new story though, so we could resolve the current issue.

Side note: seems like ASG_NAME variable is not actually used so maybe it make sense to remove it.

**Comment by ipapapa** [comment]
@cyrusmith OK I will resolve this. The IAMCredentials are load here in the [InjectedWebListener](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/defaultimpl/InjectedWebListener.java#L122). 

The IAMCredential class uses the AWS InstanceProfileCredentialsProvider(). In your local environment, you need to provide the corresponding credentials, but in AWS it will automatically be provided by the environment/AWS. There is a section about [setting up AWS roles](https://github.com/Netflix/dynomite-manager/wiki/Configuration#setting-up-aws-roles) in the documentation. 

In other environments, you can implement the [ICredential](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/sidecore/ICredential.java) interface and bind it in the [InjectedWebListener](https://github.com/Netflix/dynomite-manager/blob/dev/dynomitemanager/src/main/java/com/netflix/dynomitemanager/defaultimpl/InjectedWebListener.java)

**Comment by diegopacheco** [comment]
@ipapapa All good for me! :+1:
