### ISSUE TITLE
asg scale out is not working

### ISSUE THREAD

**Issue by diegopacheco** [Netflix/dynomite-manager#71]
@ipapapa 

I create a Dynomite-Manager / Dynomite cluster using the following versions:
Redis: 3.0.7
Dynomite: 0.5.8-5
DM: v1.0.1 from tag in GitHub

I create a cluster in AWS us-west-2 with 3 ASG one ASG per AZ. Like this:
                -node1          |       us-west-2c
                -node2          |       us-west-2a
                -node3          |       us-west-2b

One instance only per AZ, being: MIM: 1, MAX: 1, DESIRED: 1. 

It all works great I have a 3 node cluster all working fine. All 3 nodes use this token: 1383429731.

However, I want to SCALE OUT this cluster so I go to EACH ASG and increase 1 instance being: 

being: MIM: 1, MAX: 2, DESIRED: 2.

After some time I got this topology:

token:  1383429731
                -node1          |       us-west-2b
                -node2          |       us-west-2c
                -node3         |       us-west-2a
token:  3530913378
                -node4          |       us-west-2a
                -node5          |       us-west-2b

So looks like the DM did not generate the right SLOTS for the new nodes and the cluster is not correct anymore. 

In this case 1 node did not get into the clusters, sometimes is 2 nodes. Its random. I'm I doing something wrong? 

Cheers,
Diego Pacheco

**Comment by ipapapa** [comment]
Does this issue seem related to https://github.com/Netflix/dynomite-manager/issues/72 or is this totally different?

**Comment by diegopacheco** [comment]
@ipapapa I would say #71 and #72 are related but different problems. Since 71 is about adding more capacity to an AZ via ASG and 72 is about replacing existent instances on same AZ/ASG capacity.

**Comment by diegopacheco** [comment]
AS FAR as I remember you told me this feature was not implemented YET right @ipapapa  so I think you can close this.
