### ISSUE TITLE
Cold Bootstraping for ARDB RocksDB as a persistent backend?

### ISSUE THREAD

**Issue by deegoy2** [Netflix/dynomite-manager#90]
Hi, I love the work you guys have done with Dynomite, Dyno and DM. Huge fan. :)

Does Cold Bootstrapping work inherently with RocksDB as a persistent backend or is it designed only around Redis? 
If yes, is there a reference implementation?
If no, what can be done to achieve this?
Cold bootstrapping is an essential feature to have towards a fully scalable distributed persistent DB.

Also, I wanted to understand what drove the design decisions towards not implementing an **auto-scaling** consistent hash ring (and instead using a dual-write approach to achieve horizontal scalability). Was it related to the requirements at Netflix or lack of support from OSS or pluggable backends lacking full support or something else?

**Comment by deegoy2** [comment]
Gentle ping...

**Comment by ipapapa** [comment]
Yes, it does work for RocksDB. You can use something like [ARDB](https://github.com/yinqiwen/ardb) that embeds RocksDB and provides Redis API. Hence cold bootstrap is leveraging the master-slave replication. 

We have captured a few of the issues and solutions of the auto-scaling in the [Scale up and down project](https://github.com/Netflix/dynomite/projects/5). I have captured some of the notes https://github.com/Netflix/dynomite/issues/342 Dual-writer can be used if the data has TTL. Currently, we are looking for folks assisting to build the scale up and scale down functionality. If you are using Dynomite as a cache the steps that I describe should be enough.

**Comment by deegoy2** [comment]
Thank you @ipapapa :D
